import assert from "node:assert/strict";
import { MONTHS, initialState, strategyDecisions, buildFromDraft, priceProgram, directCost, capacityChecks, validateDecision, studioDepreciationMonthly } from "./model.js";
assert.equal(strategyDecisions.length, 5);
assert.deepEqual(MONTHS, ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]);
assert.equal(priceProgram("Standard corporate", 2, 20), 5000);
assert.equal(priceProgram("Large corporate", 1, 20), 2500);
assert.equal(priceProgram("Large corporate", 1, 21), 3150);
assert.equal(priceProgram("Large corporate", 1, 30), 3150);
assert.equal(priceProgram("Large corporate", 1, 31), 3800);
assert.equal(priceProgram("Large corporate", 1, 60), 5100);
assert.equal(priceProgram("Large corporate", 1, 61), 5750);
assert.equal(priceProgram("Large corporate", 1, 90), 7050);
assert.equal(priceProgram("Large corporate", 1, 100), 7700);
assert.equal(priceProgram("Large corporate", 1, 110), 7700);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jun" }).instructor, 700);
assert.equal(directCost({ type: "Standard corporate", days: 1, participants: 20, month: "Jul" }).instructor, 770);
assert.equal(directCost({ type: "Large corporate", days: 2, participants: 60, month: "Jun" }).assistants, 350);
assert.equal(directCost({ type: "Open", days: 1, participants: 20, month: "Jan", seatPrice: 500 }).venue, 600);
assert.equal(capacityChecks().length, MONTHS.length);
assert.equal(studioDepreciationMonthly, 25000 / 60);
assert.equal(validateDecision({ action: "x" }).valid, false);
assert.equal(validateDecision({ action: "x", startMonth: "Jan", cost: "0", effect: "0", evidence: "source", revenueDelta: [], directDelta: [], opexDelta: [] }).valid, true);
const { p1, p2 } = buildFromDraft(initialState.part1, strategyDecisions);
assert.equal(p1.revenue[2], 15000);
assert.equal(p1.revenue[5], 12750);
assert.equal(p1.revenue[8], 17000);
assert.equal(p1.revenue[10], 16800);
assert.equal(p1.totals.revenue, 146650);
assert.equal(p2.revenue[5], 22750);
assert.equal(p2.totals.revenue, 216650);
assert.equal(validateDecision(strategyDecisions[0]).valid, true);
console.log("Domain tests passed.");
